export type AppointmentType =
  | 'TAX CONSULTATION'
  | 'FINANCIAL AID APPLICATION'
  | 'BENEFITS ENROLLMENT'
  | 'DEBT MANAGEMENT AND COUNSELING'
  | 'INVESTMENT AND RETIREMENT PLANNING'
  | 'BUSINESS FINANCING'
  | 'FINANCIAL LITERACY WORKSHOPS'
  | 'HOUSING ASSISTANCE';